UNSET START_TIME;
SET START_TIME = (SELECT DATEADD(day, -7, CURRENT_DATE()));

WITH PREP AS
(
SELECT
     COALESCE(USER_NAME, 'ALL') AS USER
    ,COUNT(*) AS QUERY_CNT
    ,SUM(CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 1 END)/COUNT(*) AS SUCESS_RATIO_PER_USER
    ,SUM(SUM(CASE WHEN EXECUTION_STATUS = 'SUCCESS' THEN 1 END)) OVER()/SUM(COUNT(*)) OVER() AS OVERALL_SUCCESS_RATIO
FROM
    SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE
    START_TIME::DATE >= $START_TIME
GROUP BY
    ROLLUP(USER_NAME)
)
SELECT
     USER
    ,QUERY_CNT
    ,ROUND(SUCESS_RATIO_PER_USER * 100, 2) AS SUCCESS_RATIO
    ,CASE
        WHEN SUCESS_RATIO_PER_USER > OVERALL_SUCCESS_RATIO
            THEN 'ABOVE AVERAGE'
        WHEN SUCESS_RATIO_PER_USER < OVERALL_SUCCESS_RATIO
            THEN 'BELOW AVERAGE'
        ELSE 'AVERAGE'
     END AS SUCESS_RATIO_CATEGORY
    ,DENSE_RANK() OVER(ORDER BY SUCESS_RATIO_PER_USER DESC, QUERY_CNT DESC) AS RANKING
FROM
    PREP
WHERE
    USER != 'ALL'
ORDER BY
     RANKING;
