CREATE OR REPLACE TEMP TABLE TEST AS
SELECT 'DE' AS MARKET, 3 AS ORDERS
UNION ALL
SELECT 'US' AS MARKET, 4 AS ORDERS;

WITH TMP AS
(
SELECT
	 *
	,REPEAT('X', ORDERS-1) AS _SPLIT_ROWS
FROM
	TEST 
)
SELECT
	MARKET,
	1 AS ORDERS
FROM
	TMP
CROSS JOIN
	LATERAL SPLIT_TO_TABLE(TMP._SPLIT_ROWS, 'X');