CREATE OR REPLACE TEMP TABLE TMP (COL_A STRING, COL_B INTEGER, COL_C STRING, COL_D INTEGER);
INSERT INTO TMP SELECT 'A', 1, 'B', 2;
INSERT INTO TMP SELECT 'C', 3, 'D', 4;
INSERT INTO TMP SELECT 'E', 5, 'F', 6;
INSERT INTO TMP SELECT 'G', 7, 'H', 8;

SELECT
	*
	,ARRAY_CONSTRUCT(*) AS ALL_COLS
FROM
	TMP
WHERE
	ARRAY_CONTAINS('E'::VARIANT, ALL_COLS);