CREATE OR REPLACE TEMP TABLE TMP (NUM INT, STR STRING);
INSERT INTO TMP SELECT 1, 'X';
INSERT INTO TMP SELECT 2, 'Y';
INSERT INTO TMP SELECT 3, 'Z';
INSERT INTO TMP SELECT 4, 'X';
INSERT INTO TMP SELECT 5, 'Y';

SELECT
	STR,
	ARRAY_AGG(NUM),
	AVG(NUM)
FROM
	TMP
GROUP BY
	STR
ORDER BY	
	STR;

SELECT
	*
FROM
	TABLE(GET_QUERY_OPERATOR_STATS(LAST_QUERY_ID()));