CREATE OR REPLACE TEMP TABLE S_INVOICE(INVC_NO VARCHAR, CUST_NO VARCHAR NOT NULL, INVC_AMT NUMBER, INVC_DT DATE, LATE_FEE BOOLEAN);
CREATE OR REPLACE TEMP TABLE RAW_INVOICE(INVC_NO VARCHAR, CUST_NO VARCHAR, INVC_AMT VARCHAR, INVC_DT VARCHAR, LATE_FEE VARCHAR);
CREATE OR REPLACE TEMP TABLE INVOICE_ERROR(INVC_NO VARCHAR, CUST_NO VARCHAR, INVC_AMT VARCHAR, INVC_DT VARCHAR, LATE_FEE VARCHAR, ERROR_MSG ARRAY);

INSERT INTO RAW_INVOICE VALUES
('1', '1', '10', '2022-01-01','TRUE'),
('2', '1', '11', '2022-01-02','FALSE'),
('2', '1', 'X', '2022-01-02','FALSE'),
('2', '1', '11', '2022-01-02','WRONG'),
('1', NULL, '10', '2022-01-01','WRONG'),
('1', NULL, '10', 'XYZ','WRONG');

INSERT FIRST
WHEN
	(TRY_TO_NUMBER(INVC_AMT) IS NULL AND INVC_AMT IS NOT NULL)
OR
	(CUST_NO IS NULL)
OR
	(TRY_TO_DATE(INVC_DT) IS NULL AND INVC_DT IS NOT NULL)
OR
	(TRY_TO_BOOLEAN(LATE_FEE) IS NULL AND LATE_FEE IS NOT NULL)
THEN
	INTO INVOICE_ERROR
	VALUES (INVC_NO, CUST_NO, INVC_AMT, INVC_DT, LATE_FEE, [CUST_NO_DETAIL, INVC_AMT_DETAIL, INVC_DT_DETAIL , LATE_FEE_DETAIL])
ELSE
	INTO S_INVOICE
	VALUES (INVC_NO, CUST_NO, INVC_AMT, INVC_DT, LATE_FEE)
SELECT
	 INVC_NO
	,CUST_NO
	,INVC_AMT
	,INVC_DT
	,LATE_FEE
	,CASE WHEN CUST_NO IS NULL THEN 'CUST_NO IS NULL' END AS CUST_NO_DETAIL
	,CASE WHEN TRY_TO_NUMBER(INVC_AMT) IS NULL THEN 'INVC_AMT HAS WRONG FORMAT' END AS INVC_AMT_DETAIL
	,CASE WHEN TRY_TO_DATE(INVC_DT) IS NULL THEN 'INVC_DT HAS WRONG FORMAT' END AS INVC_DT_DETAIL
	,CASE WHEN TRY_TO_BOOLEAN(LATE_FEE) IS NULL THEN 'LATE FEE HAS WRONG FORMAT' END LATE_FEE_DETAIL
FROM
	RAW_INVOICE;

SELECT
	*
FROM
	INVOICE_ERROR;

SELECT
	*
FROM
	S_INVOICE;