USE ROLE ACCOUNTADMIN;

-- FIND ACTIVE ROLES IN DB

SELECT
	*
FROM
	SNOWFLAKE.ACCOUNT_USAGE.ROLES
WHERE
	DELETED_ON IS NULL;
	
-- QUERY TO FIND PRIVELEGES

SELECT
	 GRANTOR
	,GRANTEE
	,OBJECT_CATALOG AS DB_NAME
	,OBJECT_SCHEMA AS DB_SCHEMA
	,OBJECT_TYPE
	,PRIVILEGE_TYPE
FROM
	INFORMATION_SCHEMA.OBJECT_PRIVILEGES;

-- FIND PRIVILEGES ASSIGNED ROLE

SELECT
	 PRIVILEGE
	,GRANTED_ON
	,NAME AS OBJECT_NAME
	,TABLE_CATALOG AS DB_NAME
	,TABLE_SCHEMA AS SCHEMA_NAME
	,GRANTEE_NAME AS ROLE_ASSIGNED_PRIV
	,GRANTED_BY
FROM
	SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES;
	
-- ROLES ASSIGNED TO USERS:

SELECT
	*
FROM
	SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS;

-- USERS WHO HAVE NOT LOGGED WITHIN 90 DAYS AFER ACCOUNT CREATION

SHOW USERS;

SELECT
	*
FROM
	TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE
	"last_success_login" IS NULL
AND
	DATEDIFF('DAY', "created_on", CURRENT_DATE()) > 90;
	
-- FIND OUT THE FULL TABLE SCAN QUERIES APPROX. 95%

SELECT
	 QUERY_TEXT
	,DATABASE_NAME
	,QUERY_TYPE
	,WAREHOUSE_NAME
	,BYTES_SCANNED
	,PARTITIONS_SCANNED
	,PARTITIONS_TOTAL
FROM
	SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY

WHERE PARTITIONS_SCANNED > (PARTITIONS_TOTAL * 0.95);

-- WAREHOUSE METERING

SELECT
	 START_TIME
	,END_TIME
	,WAREHOUSE_NAME
	,CREDITS_USED AS CREDITS_BILLED
	,CREDITS_USED_COMPUTE AS CREDITS_USED
	,CREDITS_USED_CLOUD_SERVICES AS CREDITS_CLOUD_SERVICES
FROM
	SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
ORDER BY
	START_TIME;

-- SWITCH ROLE, JUST TO BE SAFE

USE ROLE SYSADMIN;